services:
  stockflow.api:
    image: stockflow.api
    container_name: Stockflow.API
    build:
      context: .
      dockerfile: StockFlow.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - stockflow-db
 
  stockflow-db:
    image: postgres:17
    container_name: Stockflow.Db
    environment:
      - POSTGRES_DB=stockflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        
  stockflow-seq:
    image: datalust/seq:2024.3
    container_name: Stockflow.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"

  stockflow-redis:
    image: redis:latest
    container_name: Stockflow.Redis
    restart: always
    ports:
     - 6379:6379

